version: '3'
services:
  db:
    image: 'postgres:13'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smalt_dev
  api:
    stdin_open: true
    depends_on:
      - db
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /opt/app/deps
      - /opt/app/_build
      - .:/opt/app
    environment:
      - DB_HOST=db
    ports:
      - '4000:4000'
