version: '3'
services:
  db:
    image: 'postgres:13'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smalt_dev
  api:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /opt/app/deps
      - /opt/app/_build
      - /opt/app/apps/client/ui/node_modules
      - .:/opt/app
    environment:
      - DB_HOST=db
    ports:
      - '4000:4000'
  client:
    depends_on:
      - api
    build:
      context: apps/client/ui
    volumes:
      - /opt/app/node_modules
      - ./apps/client/ui:/opt/app
    ports:
      - '3000:3000'
