FROM bitwalker/alpine-elixir-phoenix:latest

EXPOSE 4000
ENV PORT=4000

ENV HEX_HTTP_TIMEOUT=120

COPY apps/client/mix.exs apps/client/mix.exs
COPY apps/graph/mix.exs apps/graph/mix.exs
COPY apps/smalt/mix.exs apps/smalt/mix.exs
COPY apps/smalt_web/mix.exs apps/smalt_web/mix.exs
COPY mix.exs mix.lock ./
RUN mix do deps.get, compile

ADD . .

CMD ["mix", "phx.server"]
